

urls = {
    "Leicester": "https://www.rightmove.co.uk/property-for-sale/find.html?searchLocation=Leicester%2C+Leicestershire&useLocationIdentifier=true&locationIdentifier=REGION%5E789&radius=10.0&minPrice=50000&maxPrice=15000000&minBedrooms=0&maxBedrooms=10&propertyTypes=detached%2Csemi-detached%2Cterraced&maxDaysSinceAdded=1&_includeSSTC=on",
    "Birmingham": "https://www.rightmove.co.uk/property-for-sale/find.html?searchLocation=Birmingham&useLocationIdentifier=true&locationIdentifier=REGION%5E162&radius=10.0&minPrice=50000&maxPrice=20000000&minBedrooms=0&maxBedrooms=10&_includeSSTC=on&index=960&sortType=2&channel=BUY&transactionType=BUY&displayLocationIdentifier=Birmingham.html",
    "London": "https://www.rightmove.co.uk/property-for-sale/find.html?useLocationIdentifier=true&locationIdentifier=REGION%5E87490&minPrice=50000&maxPrice=20000000&minBedrooms=0&maxBedrooms=10&_includeSSTC=on&index=0&sortType=2&channel=BUY&transactionType=BUY&displayLocationIdentifier=London-87490.html",
    "Glasgow": "https://www.rightmove.co.uk/property-for-sale/find.html?useLocationIdentifier=true&locationIdentifier=REGION%5E550&minPrice=50000&maxPrice=20000000&minBedrooms=0&maxBedrooms=10&_includeSSTC=on&index=0&sortType=2&channel=BUY&transactionType=BUY&displayLocationIdentifier=Glasgow.html",
    "Edinburgh": "https://www.rightmove.co.uk/property-for-sale/find.html?useLocationIdentifier=true&locationIdentifier=REGION%5E475&minPrice=50000&maxPrice=20000000&minBedrooms=0&maxBedrooms=10&_includeSSTC=on&index=0&sortType=2&channel=BUY&transactionType=BUY&displayLocationIdentifier=Edinburgh.html",
    "Newcastle": "https://www.rightmove.co.uk/property-for-sale/find.html?useLocationIdentifier=true&locationIdentifier=REGION%5E984&minPrice=50000&maxPrice=20000000&minBedrooms=0&maxBedrooms=10&_includeSSTC=on&index=0&sortType=2&channel=BUY&transactionType=BUY&displayLocationIdentifier=Newcastle-Upon-Tyne.html",
    "Bristol": "https://www.rightmove.co.uk/property-for-sale/find.html?useLocationIdentifier=true&locationIdentifier=REGION%5E219&minPrice=50000&maxPrice=20000000&minBedrooms=0&maxBedrooms=10&_includeSSTC=on&index=0&sortType=2&channel=BUY&transactionType=BUY&displayLocationIdentifier=Bristol.html",
    "Manchester": "https://www.rightmove.co.uk/property-for-sale/find.html?useLocationIdentifier=true&locationIdentifier=REGION%5E904&minPrice=50000&maxPrice=20000000&minBedrooms=0&maxBedrooms=10&_includeSSTC=on&index=0&sortType=2&channel=BUY&transactionType=BUY&displayLocationIdentifier=Manchester.html",
    "Notingham": "https://www.rightmove.co.uk/property-for-sale/find.html?useLocationIdentifier=true&locationIdentifier=REGION%5E1019&minPrice=50000&maxPrice=20000000&minBedrooms=0&maxBedrooms=10&_includeSSTC=on&index=0&sortType=2&channel=BUY&transactionType=BUY&displayLocationIdentifier=Nottingham.html",
    "Sheffield": "https://www.rightmove.co.uk/property-for-sale/find.html?useLocationIdentifier=true&locationIdentifier=REGION%5E1195&minPrice=50000&maxPrice=20000000&minBedrooms=0&maxBedrooms=10&_includeSSTC=on&index=0&sortType=2&channel=BUY&transactionType=BUY&displayLocationIdentifier=Sheffield.html",
    "Liverpool": "https://www.rightmove.co.uk/property-for-sale/find.html?useLocationIdentifier=true&locationIdentifier=REGION%5E813&minPrice=50000&maxPrice=20000000&minBedrooms=0&maxBedrooms=10&_includeSSTC=on&index=0&sortType=2&channel=BUY&transactionType=BUY&displayLocationIdentifier=Liverpool.html",
    "Cardiff": "https://www.rightmove.co.uk/property-for-sale/find.html?useLocationIdentifier=true&locationIdentifier=REGION%5E281&minPrice=50000&maxPrice=20000000&minBedrooms=0&maxBedrooms=10&_includeSSTC=on&index=0&sortType=2&channel=BUY&transactionType=BUY&displayLocationIdentifier=Cardiff.html",
    "Belfast": "https://www.rightmove.co.uk/property-for-sale/find.html?useLocationIdentifier=true&locationIdentifier=REGION%5E133&minPrice=50000&maxPrice=20000000&minBedrooms=0&maxBedrooms=10&_includeSSTC=on&index=0&sortType=2&channel=BUY&transactionType=BUY&displayLocationIdentifier=Belfast.html",
    "Leeds": "https://www.rightmove.co.uk/property-for-sale/find.html?useLocationIdentifier=true&locationIdentifier=REGION%5E787&minPrice=50000&maxPrice=20000000&minBedrooms=0&maxBedrooms=10&_includeSSTC=on&index=0&sortType=2&channel=BUY&transactionType=BUY&displayLocationIdentifier=Leeds.html",
    "Southampton": "https://www.rightmove.co.uk/property-for-sale/find.html?useLocationIdentifier=true&locationIdentifier=REGION%5E1231&minPrice=50000&maxPrice=20000000&minBedrooms=0&maxBedrooms=10&_includeSSTC=on&index=0&sortType=2&channel=BUY&transactionType=BUY&displayLocationIdentifier=Southampton.html"
}


